# Generated by Django 6.0 on 2026-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='attachment_pics/'),
        ),
    ]
